In [2]:
import numpy as np

# Q1.a

In [2]:
a=np.array([1,2,3,6,4,5])

In [3]:
b=np.flip(a)

In [4]:
print(b)

[5 4 6 3 2 1]


# Q1.b

In [6]:
ar=np.array([[1,2,3],[2,4,5],[1,2,3]])

In [8]:
ar.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

# Q1.c

In [9]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[1,2],[3,4]])

In [10]:
np.array_equal(a1,a2)

True

# Q1.d

In [11]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

In [12]:
np.bincount(x).argmax()

1

In [13]:
np.where(x==np.bincount(x).argmax())[0]

array([0, 5, 7, 8, 9], dtype=int64)

# Q1.e

In [14]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

In [15]:
np.sum(gfg)

45

In [16]:
np.sum(gfg,axis=1)

matrix([[14],
        [16],
        [15]])

In [17]:
np.sum(gfg,axis=0)

matrix([[20,  9, 16]])

# Q1.f

In [18]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

In [19]:
np.trace(n_array)

176

In [20]:
np.linalg.eig(n_array)

(array([98.16835147, 28.097044  , 49.73460452]),
 array([[ 0.4574917 ,  0.34637121, -0.15017693],
        [ 0.28447814, -0.72784061, -0.4852124 ],
        [ 0.84248058,  0.59184038,  0.8614034 ]]))

In [21]:
np.linalg.inv(n_array)

array([[ 0.02404141, -0.00911212, -0.00444671],
       [-0.01667882,  0.02966905,  0.0024785 ],
       [ 0.00631287, -0.01603732,  0.01217379]])

In [22]:
np.linalg.det(n_array)

137180.0000000001

# Q1.g

In [23]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

In [24]:
np.matmul(p,q)

array([[16, 19],
       [26, 31]])

In [25]:
np.cov(p,q)

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [26]:
pp = np.array([[1, 2], [2, 3], [4, 5]])
qq = np.array([[4, 5, 1], [6, 7, 2]])

In [27]:
np.matmul(pp,qq)

array([[16, 19,  5],
       [26, 31,  8],
       [46, 55, 14]])

In [29]:
qq=qq.T
np.cov(pp,qq)

array([[0.5, 0.5, 0.5, 1. , 1. , 0.5],
       [0.5, 0.5, 0.5, 1. , 1. , 0.5],
       [0.5, 0.5, 0.5, 1. , 1. , 0.5],
       [1. , 1. , 1. , 2. , 2. , 1. ],
       [1. , 1. , 1. , 2. , 2. , 1. ],
       [0.5, 0.5, 0.5, 1. , 1. , 0.5]])

# Q1.h

In [30]:
x1 = np.array([[2, 3, 4], [3, 2, 9]])
y1 = np.array([[1, 5, 0], [5, 10, 3]])

In [31]:
np.inner(x1,y1)

array([[17, 52],
       [13, 62]])

In [32]:
np.outer(x1,y1)

array([[ 2, 10,  0, 10, 20,  6],
       [ 3, 15,  0, 15, 30,  9],
       [ 4, 20,  0, 20, 40, 12],
       [ 3, 15,  0, 15, 30,  9],
       [ 2, 10,  0, 10, 20,  6],
       [ 9, 45,  0, 45, 90, 27]])

In [33]:
np.array(np.meshgrid(x1, y1)).T.reshape(-1, 2)

array([[ 2,  1],
       [ 2,  5],
       [ 2,  0],
       [ 2,  5],
       [ 2, 10],
       [ 2,  3],
       [ 3,  1],
       [ 3,  5],
       [ 3,  0],
       [ 3,  5],
       [ 3, 10],
       [ 3,  3],
       [ 4,  1],
       [ 4,  5],
       [ 4,  0],
       [ 4,  5],
       [ 4, 10],
       [ 4,  3],
       [ 3,  1],
       [ 3,  5],
       [ 3,  0],
       [ 3,  5],
       [ 3, 10],
       [ 3,  3],
       [ 2,  1],
       [ 2,  5],
       [ 2,  0],
       [ 2,  5],
       [ 2, 10],
       [ 2,  3],
       [ 9,  1],
       [ 9,  5],
       [ 9,  0],
       [ 9,  5],
       [ 9, 10],
       [ 9,  3]])

# Q2a

In [3]:
ax=np.array([[1,-2,3],[-4,5,-6]])

In [4]:
np.abs(ax)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.percentile(ax.flatten(),[25,50,75])

array([-3.5, -0.5,  2.5])

In [7]:
np.mean(ax.flatten())


-0.5

In [8]:
np.median(ax.flatten())


-0.5

In [9]:
np.std(ax.flatten())

3.8622100754188224

In [10]:
np.mean(ax,axis=0)

array([-1.5,  1.5, -1.5])

In [11]:
np.median(ax,axis=0)

array([-1.5,  1.5, -1.5])

In [12]:
np.std(ax,axis=0)

array([2.5, 3.5, 4.5])

In [13]:
np.mean(ax,axis=1)

array([ 0.66666667, -1.66666667])

In [14]:
np.median(ax,axis=1)

array([ 1., -4.])

In [15]:
np.std(ax,axis=1)

array([2.05480467, 4.78423336])

# Q2b

In [16]:
 av= np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

In [17]:
np.floor(av)

array([-2., -2., -1.,  0.,  1.,  1.,  3.])

In [18]:
np.ceil(av)

array([-1., -1., -0.,  1.,  2.,  2.,  3.])

In [19]:
np.trunc(av)

array([-1., -1., -0.,  0.,  1.,  1.,  3.])

In [20]:
np.round(av)

array([-2., -2., -0.,  0.,  2.,  2.,  3.])

# Q3a

In [21]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

In [22]:
np.sort(array)

array([ 10,  16,  16,  52,  54,  62, 453])

In [23]:
np.argsort(array)

array([0, 3, 4, 1, 5, 2, 6], dtype=int64)

In [24]:
np.partition(array,3)[3]

52

In [25]:
np.partition(array,-5)[-5]

16

# Q3b

In [26]:
z=np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

In [27]:
z[z.astype(int)==z]

array([1., 2., 3., 2.])

In [28]:
z[z.astype(int)!=z]

array([1.2, 2.2])

# Q4

In [37]:
import PIL.Image as Image

In [44]:
def img_to_array(p,op):
    img=np.array(Image.open(p))
    if len(img.shape) == 3 and img.shape[2] == 3:
            img_array = img
    if len(img.shape) == 2:
            img_array = img.reshape(-1,img.shape[-1])
    img_array =img_array.flatten()
       
    np.savetxt(op, img_array, fmt='%d')

In [45]:
img_to_array("download.jpg","op.txt")